# Generated by Django 5.2.5 on 2025-09-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='comment', max_length=200),
        ),
    ]
