# Generated by Django 5.2.5 on 2025-08-24 11:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_description', models.CharField(blank=True, default='', max_length=200)),
                ('contact_name', models.CharField(blank=True, default='', help_text='Primary contact person name.', max_length=100)),
                ('email', models.CharField(blank=True, default='', help_text='Contact email address.', max_length=200)),
                ('phone', models.CharField(blank=True, default='', help_text='Primary phone number.', max_length=50)),
                ('website', models.CharField(blank=True, default='', help_text='Website URL.', max_length=200)),
                ('tax_id', models.CharField(blank=True, default='', help_text='Tax/VAT identifier.', max_length=50)),
                ('address_line1', models.CharField(blank=True, default='', help_text='Address line 1.', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', help_text='Address line 2.', max_length=200)),
                ('postal_code', models.CharField(blank=True, default='', help_text='Postal/ZIP code.', max_length=20)),
                ('city', models.CharField(blank=True, default='', help_text='City.', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code.', max_length=2)),
                ('payment_terms', models.CharField(blank=True, default='', help_text='Payment terms shorthand (e.g., NET30).', max_length=50)),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark as preferred supplier.')),
                ('lead_time_days', models.SmallIntegerField(default=0, help_text='Typical lead time in days.')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='core.organization')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'constraints': [models.UniqueConstraint(fields=('organization', 'supplier_code'), name='uniq_supplier_org_code'), models.UniqueConstraint(fields=('organization', 'id'), name='uniq_supplier_org_id')],
            },
        ),
    ]
