# Generated by Django 5.2.5 on 2025-08-25 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', help_text='running, success, failed', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(help_text='Supplier this import run belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='partners.supplier')),
            ],
            options={
                'db_table': 'partners_import_run',
            },
        ),
    ]
