# Generated by Django 5.2.5 on 2025-08-25 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_importrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Unique identifier from the external system (if available).', max_length=255)),
                ('payload', models.JSONField(help_text='Full raw payload from the external source (JSON or converted dict).')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this record was fetched from the external system.')),
                ('supplier', models.ForeignKey(help_text='Supplier that delivered this raw record.', on_delete=django.db.models.deletion.CASCADE, related_name='import_raw_records', to='partners.supplier')),
            ],
            options={
                'db_table': 'partners_import_raw_record',
                'indexes': [models.Index(fields=['supplier', 'external_id'], name='partners_im_supplie_409836_idx')],
                'unique_together': {('supplier', 'external_id')},
            },
        ),
    ]
