# Generated by Django 5.2.5 on 2025-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_importrawrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when raw records were processed into ERP tables.', null=True),
        ),
    ]
