# Generated by Django 5.2.5 on 2025-08-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_importrun_processed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importrun',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='ImportRawRecord',
        ),
        migrations.DeleteModel(
            name='ImportRun',
        ),
    ]
