# Generated by Django 5.2.5 on 2025-08-24 10:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=16, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('rate_date', models.DateField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_rates', to='core.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_rates', to='core.currency')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('base', 'quote', 'rate_date'), name='uniq_currency_rate'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='ck_currency_rate_positive')],
            },
        ),
    ]
