# Generated by Django 5.2.5 on 2025-08-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_group_code', models.CharField(help_text='Price group code (unique within organization).', max_length=20)),
                ('price_group_description', models.CharField(blank=True, help_text='Optional description/name of the price group.', max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'verbose_name': 'Price Group',
                'verbose_name_plural': 'Price Groups',
                'constraints': [models.UniqueConstraint(fields=('organization', 'price_group_code'), name='uniq_price_group_org_code')],
            },
        ),
    ]
