# Generated by Django 5.2.5 on 2025-08-24 10:50

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_productmedia_table_alter_productvariant_table'),
        ('core', '0002_organization'),
        ('pricing', '0002_pricegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_list_code', models.CharField(max_length=20)),
                ('price_list_description', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='core.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPriceList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='sale', max_length=20)),
                ('priority', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_price_lists', to='catalog.channel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_price_lists', to='core.organization')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_price_lists', to='pricing.pricelist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'price_list_code'), name='uniq_price_list_org_code'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='uniq_price_list_org_id'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['S', 'P'])), name='ck_price_list_kind'),
        ),
        migrations.AddConstraint(
            model_name='channelpricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'channel', 'price_list'), name='uniq_chpl_org_chan_pl'),
        ),
        migrations.AddConstraint(
            model_name='channelpricelist',
            constraint=models.UniqueConstraint(fields=('organization', 'channel', 'role', 'priority'), name='uniq_chpl_org_chan_role_pri'),
        ),
    ]
