# Generated by Django 5.2.5 on 2025-08-24 11:07

import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_pricegroup_organization_productvariantprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelpricelist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'db_table': 'tax_class',
                'indexes': [models.Index(fields=['rate'], name='idx_tax_class_rate')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 1)), name='ck_tax_class_rate')],
            },
        ),
    ]
