# Generated by Django 5.2.5 on 2025-08-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_channelpricelist_id_alter_pricelist_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariantPrice',
        ),
    ]
