# Generated by Django 5.2.5 on 2025-08-24 16:33

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_productgroup_uniq_product_group_org_item_group_code_and_more'),
        ('core', '0002_organization'),
        ('pricing', '0006_delete_productvariantprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannelVariantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('need_update', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('channel_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_channel_variant_prices', to='catalog.channelvariant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_channel_variant_prices', to='core.organization')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_channel_variant_prices', to='pricing.pricelist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'price_list', 'channel_variant', 'valid_from'), name='uniq_chanel_var_price_valid'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_price_amount_nonneg')],
            },
        ),
    ]
