# Generated by Django 5.2.5 on 2025-08-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_saleschannelvariantprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelPriceList',
        ),
    ]
