# Generated by Django 5.2.5 on 2025-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_delete_channelpricelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleschannelvariantprice',
            old_name='amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='saleschannelvariantprice',
            name='need_update',
            field=models.BooleanField(default=False),
        ),
    ]
