# Generated by Django 5.2.5 on 2025-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_channelvariant_uniq_channel_variant_ext'),
        ('core', '0002_organization'),
        ('pricing', '0009_rename_amount_saleschannelvariantprice_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleschannelvariantprice',
            name='ck_price_amount_nonneg',
        ),
        migrations.AddConstraint(
            model_name='saleschannelvariantprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ck_price_price_nonneg'),
        ),
    ]
