# Generated by Django 5.2.5 on 2025-08-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_channelvariant_uniq_channel_variant_ext'),
        ('core', '0002_organization'),
        ('pricing', '0011_remove_saleschannelvariantprice_ck_price_price_nonneg_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleschannelvariantprice',
            name='uniq_chanel_var_price_valid',
        ),
        migrations.AddConstraint(
            model_name='saleschannelvariantprice',
            constraint=models.UniqueConstraint(fields=('organization', 'price_list', 'channel_variant', 'valid_from'), name='uniq_channel_var_price_valid'),
        ),
    ]
