# Generated by Django 5.2.5 on 2025-08-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_productvariant_available_stock_and_more'),
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierproduct',
            name='uniq_spp_supplier_sku',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='available_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Availability flag as provided by supplier.'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='shipping_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('organization', 'variant', 'supplier'), name='uniq_spp_supplier_variant'),
        ),
    ]
