# Generated by Django 5.2.5 on 2025-08-27 07:44

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productvariant_available_stock_and_more'),
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        ('procurement', '0002_remove_supplierproduct_uniq_spp_supplier_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code (e.g. EUR, USD).', max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Net purchase price per unit (without VAT).', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_quantity', models.DecimalField(decimal_places=3, default=1, help_text='Minimum quantity for this price tier.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
            options={
                'verbose_name': 'Supplier Price',
                'verbose_name_plural': 'Supplier Prices',
            },
        ),
        migrations.RemoveConstraint(
            model_name='supplierproduct',
            name='ck_spp_pack_pos',
        ),
        migrations.RemoveConstraint(
            model_name='supplierproduct',
            name='ck_spp_moq_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='supplierproduct',
            name='ck_spp_lead_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='supplierproduct',
            name='uniq_spp_supplier_variant',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='shipping_free',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Marks the preferred supplier for this variant.'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='lead_time_days',
            field=models.IntegerField(default=0, help_text='Standard lead time in days until delivery.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='min_order_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Minimum order quantity (MOQ) at supplier.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='pack_size',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Number of base units in one pack as sold by supplier.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_description',
            field=models.CharField(blank=True, default='', help_text='Optional description as provided by supplier (may differ from catalog description).', max_length=500),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_sku',
            field=models.CharField(help_text='Article number / SKU as used by the supplier.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('organization', 'variant', 'supplier'), name='uniq_supplier_product'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.CheckConstraint(condition=models.Q(('pack_size__gt', 0)), name='ck_supplier_packsize_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_qty__gte', 0)), name='ck_supplier_moq_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.CheckConstraint(condition=models.Q(('lead_time_days__gte', 0)), name='ck_supplier_leadtime_nonneg'),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='supplier_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='procurement.supplierproduct'),
        ),
        migrations.AddConstraint(
            model_name='supplierprice',
            constraint=models.UniqueConstraint(fields=('supplier_product', 'currency', 'min_quantity', 'valid_from'), name='uniq_supplier_price_tier'),
        ),
    ]
