# Generated by Django 5.2.5 on 2025-08-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaseorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_description',
            field=models.CharField(blank=True, default='', help_text='Optional supplier-specific description.', max_length=200),
        ),
    ]
