# Generated by Django 5.2.5 on 2025-08-27 14:12

import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=8, null=True)),
                ('decimal_places', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_code', models.SmallIntegerField(help_text='Business code for the organization (small integer).', primary_key=True, serialize=False)),
                ('org_description', models.CharField(blank=True, help_text='Optional description/name of the organization.', max_length=200)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
