# Generated by Django 5.2.5 on 2025-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_code', models.SmallIntegerField(help_text='Business code for the organization (small integer).', primary_key=True, serialize=False)),
                ('org_description', models.CharField(blank=True, help_text='Optional description/name of the organization.', max_length=200)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
