# Generated by Django 5.2.5 on 2025-08-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_importrun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportRun',
        ),
    ]
