# Generated by Django 5.2.5 on 2025-08-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group_code', models.CharField(help_text='Product group code (unique within organization).', max_length=20)),
                ('item_group_description', models.CharField(blank=True, help_text='Optional description/name of the product group.', max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'verbose_name': 'Product Group',
                'verbose_name_plural': 'Product Groups',
                'constraints': [models.UniqueConstraint(fields=('organization', 'item_group_code'), name='uniq_product_group_org_item_group_code'), models.UniqueConstraint(fields=('organization', 'id'), name='uniq_product_group_org_id')],
            },
        ),
    ]
