# Generated by Django 5.2.5 on 2025-08-24 09:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_code', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Multiplier amount for this packing unit.', max_digits=10, null=True)),
                ('packing_short_description', models.CharField(max_length=20)),
                ('packing_description', models.CharField(blank=True, max_length=200, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'packing_code'), name='uniq_packing_packing_code_org_code')],
            },
        ),
    ]
