# Generated by Django 5.2.5 on 2025-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_topseller',
            field=models.BooleanField(default=False, help_text='Flag indicating this variant is marked as top seller in the shop.'),
        ),
    ]
