# Generated by Django 5.2.5 on 2025-08-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='eclass_code',
            field=models.CharField(blank=True, help_text='International eCl@ss classification code (e.g. 44070702).', max_length=16, null=True),
        ),
    ]
