# Generated by Django 5.2.5 on 2025-08-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_eclass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description as provided by supplier/API.', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='ean',
            field=models.CharField(blank=True, help_text='Standardized GTIN/EAN code (8, 12, 13, or 14 digits).', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, help_text='Non-standard or supplier-specific barcode (may be alphanumeric).', max_length=64, null=True),
        ),
    ]
