# Generated by Django 5.2.5 on 2025-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_packing'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_code', models.CharField(help_text='Single-letter state code.', max_length=1, primary_key=True, serialize=False)),
                ('state_description', models.CharField(blank=True, help_text='Optional description/name of the state.', max_length=100)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
    ]
