# Generated by Django 5.2.5 on 2025-08-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('origin_code', models.CharField(help_text='Single-letter origin code.', max_length=1, primary_key=True, serialize=False)),
                ('origin_description', models.CharField(blank=True, help_text='Optional description/name of the origin.', max_length=100)),
            ],
            options={
                'verbose_name': 'Origin',
                'verbose_name_plural': 'Origins',
            },
        ),
    ]
