# Generated by Django 5.2.5 on 2025-08-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_description_productvariant_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_closeout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='available_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='max_purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='min_purchase',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_steps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shipping_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full product description (rich text / HTML).', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='customs_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Standardized GTIN/EAN code (8, 12, 13, or 14 digits).', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
