# Generated by Django 5.2.5 on 2025-08-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_closeout_product_is_new_product_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Availability flag as provided by supplier API.'),
        ),
    ]
