# Generated by Django 5.2.5 on 2025-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_code', models.SmallIntegerField(help_text='Business code for the manufacturer (small integer).', primary_key=True, serialize=False)),
                ('manufacturer_description', models.CharField(blank=True, help_text='Optional description/name of the manufacturer.', max_length=200)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
    ]
