# Generated by Django 5.2.5 on 2025-08-24 10:07

import apps.catalog.models.product
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_manufacturer'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('manufacturer_part_number', models.CharField(max_length=100)),
                ('manufacturer_part_number_norm', models.GeneratedField(db_persist=True, expression=apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(django.db.models.functions.text.Lower(models.F('manufacturer_part_number')), models.Value('[ßẞ]'), models.Value('ss'), models.Value('g')), models.Value('ä'), models.Value('ae'), models.Value('g')), models.Value('ö'), models.Value('oe'), models.Value('g')), models.Value('ü'), models.Value('ue'), models.Value('g')), models.Value('[^0-9a-z]+'), models.Value(''), models.Value('g')), output_field=models.CharField(max_length=200))),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.manufacturer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_product_org_slug'), models.UniqueConstraint(fields=('organization', 'manufacturer', 'manufacturer_part_number_norm'), name='uniq_product_org_manu_mpn_norm'), models.UniqueConstraint(fields=('organization', 'id'), name='uniq_product_org_id')],
            },
        ),
    ]
