# Generated by Django 5.2.5 on 2025-08-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='max_purchase',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='min_purchase',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='purchase_steps',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='shipping_free',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
    ]
