# Generated by Django 5.2.5 on 2025-08-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_productvariant_available_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='available_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Availability flag as provided by supplier API.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='max_purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='min_purchase',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='purchase_steps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shipping_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
