# Generated by Django 5.2.5 on 2025-08-24 10:08

import apps.catalog.models.product
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_part_number_norm',
            field=models.GeneratedField(db_persist=True, expression=apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(apps.catalog.models.product.RegexpReplace(django.db.models.functions.text.Lower(models.F('manufacturer_part_number')), models.Value('[ßẞ]'), models.Value('ss'), models.Value('g')), models.Value('ä'), models.Value('ae'), models.Value('g')), models.Value('ö'), models.Value('oe'), models.Value('g')), models.Value('ü'), models.Value('ue'), models.Value('g')), models.Value('[^0-9a-z]+'), models.Value(''), models.Value('g')), output_field=models.CharField(max_length=100)),
        ),
    ]
