# Generated by Django 5.2.5 on 2025-08-24 10:15

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_manufacturer_part_number_norm'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True)),
                ('customs_code', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.origin')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.packing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.state')),
            ],
            options={
                'db_table': 'product_variant',
                'constraints': [models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='ck_variant_weight_nonneg'), models.UniqueConstraint(fields=('organization', 'sku'), name='uniq_variant_org_sku'), models.UniqueConstraint(fields=('organization', 'id'), name='uniq_variant_org_id'), models.UniqueConstraint(fields=('organization', 'product', 'packing', 'origin', 'state'), name='uniq_variant_org_product_pack_origin_state')],
            },
        ),
    ]
