# Generated by Django 5.2.5 on 2025-08-24 10:28

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productvariant'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='gallery', max_length=20)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('media_url', models.TextField()),
                ('mime', models.CharField(blank=True, max_length=100, null=True)),
                ('width_px', models.IntegerField(blank=True, null=True)),
                ('height_px', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'db_table': 'product_media',
                'indexes': [models.Index(fields=['organization'], name='idx_product_media_org'), models.Index(fields=['product'], name='idx_product_media_product'), models.Index(fields=['variant'], name='idx_product_media_variant'), models.Index(fields=['role', 'sort_order'], name='idx_product_media_role_order'), models.Index(fields=['is_active'], name='idx_product_media_active')],
            },
        ),
    ]
