# Generated by Django 5.2.5 on 2025-08-24 10:31

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_productmedia'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_code', models.CharField(max_length=20)),
                ('channel_name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='shop', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
            ],
            options={
                'db_table': 'channel',
                'constraints': [models.UniqueConstraint(fields=('organization', 'channel_code'), name='uniq_channel_org_code'), models.UniqueConstraint(fields=('organization', 'id'), name='uniq_channel_org_id')],
            },
        ),
    ]
