# Generated by Django 5.2.5 on 2025-08-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_channel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table=None,
        ),
    ]
