# Generated by Django 5.2.5 on 2025-08-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_channel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmedia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table=None,
        ),
    ]
