# Generated by Django 5.2.5 on 2025-08-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_manufacturer_and_more'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='core.organization'),
        ),
    ]
