# Generated by Django 5.2.5 on 2025-08-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_channel_base_currency_and_more'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packings', to='core.organization'),
        ),
    ]
