# Generated by Django 5.2.5 on 2025-08-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_packing_organization'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_groups', to='core.organization'),
        ),
    ]
