# Generated by Django 5.2.5 on 2025-08-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_productgroup_organization'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_media', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_media', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_media', to='catalog.productvariant'),
        ),
    ]
