# Generated by Django 5.2.5 on 2025-08-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_productmedia_organization_and_more'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='catalog.origin'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='packing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='catalog.packing'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='catalog.state'),
        ),
    ]
