# Generated by Django 5.2.5 on 2025-08-24 12:13

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_productvariant_organization_and_more'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('need_shop_update', models.BooleanField(default=False)),
                ('shop_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_variant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_variants', to='catalog.channel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_variants', to='core.organization')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_variants', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'channel', 'variant'), name='uniq_channel_variant'), models.UniqueConstraint(condition=models.Q(('shop_variant_id__isnull', False), models.Q(('shop_variant_id', ''), _negated=True)), fields=('channel', 'shop_variant_id'), name='uniq_channel_variant_ext')],
            },
        ),
    ]
