# Generated by Django 5.2.5 on 2025-08-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_channelvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='item_group_code',
            new_name='product_group_code',
        ),
        migrations.RenameField(
            model_name='productgroup',
            old_name='item_group_description',
            new_name='product_group_description',
        ),
    ]
