# Generated by Django 5.2.5 on 2025-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_rename_item_group_code_productgroup_product_group_code_and_more'),
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productgroup',
            name='uniq_product_group_org_item_group_code',
        ),
        migrations.AddConstraint(
            model_name='productgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'product_group_code'), name='uniq_product_group_org_item_group_code'),
        ),
    ]
