# Generated by Django 5.2.5 on 2025-08-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_productgroup_uniq_product_group_org_item_group_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='channelvariant',
            name='uniq_channel_variant_ext',
        ),
    ]
