# Generated by Django 5.2.5 on 2025-08-25 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0006_remove_importrun_supplier_delete_importrawrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short machine-readable code (e.g., 'file', 'api').", max_length=20, unique=True)),
                ('description', models.CharField(help_text='Human-readable description of the source type.', max_length=100)),
            ],
            options={
                'verbose_name': 'Import Source Type',
                'verbose_name_plural': 'Import Source Types',
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(blank=True, help_text='Absolute or relative path to the source file that was imported.', max_length=500, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', help_text='running, success, failed', max_length=20)),
                ('total_records', models.IntegerField(blank=True, help_text='Number of raw records fetched in this run.', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Marks whether this run has already been processed into ERP tables.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when raw records were processed into ERP tables.', null=True)),
                ('supplier', models.ForeignKey(help_text='Supplier this import run belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='partners.supplier')),
                ('source_type', models.ForeignKey(help_text='Type of source for this import (e.g., file, API).', on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='imports.importsourcetype')),
            ],
            options={
                'verbose_name': 'Import Run',
                'verbose_name_plural': 'Import Runs',
            },
        ),
        migrations.CreateModel(
            name='ImportRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(help_text='Sequential line number within the import run (starting at 1).')),
                ('payload', models.JSONField(help_text='Full raw payload from the external source (JSON or converted dict).')),
                ('import_run', models.ForeignKey(help_text='Import run this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='imports.importrun')),
            ],
            options={
                'verbose_name': 'Import Raw Record',
                'verbose_name_plural': 'Import Raw Records',
                'constraints': [models.UniqueConstraint(fields=('import_run', 'line_number'), name='uniq_import_run_line')],
            },
        ),
    ]
