# Generated by Django 5.2.5 on 2025-08-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('imports', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMapSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('valid_from', models.DateField(help_text='Date from which this mapping is valid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_map_sets', to='core.organization')),
                ('source_type', models.ForeignKey(help_text='Import source type (e.g., file, API, CSV, Excel).', on_delete=django.db.models.deletion.PROTECT, related_name='import_map_sets', to='imports.importsourcetype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_map_sets', to='partners.supplier')),
            ],
            options={
                'verbose_name': 'Import Map Set',
                'verbose_name_plural': 'Import Map Sets',
            },
        ),
        migrations.CreateModel(
            name='ImportMapDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(help_text="Path in the source payload (e.g., 'translated.name', 'Artikelnummer').", max_length=255)),
                ('target_path', models.CharField(help_text="Path in the standardized dict (e.g., 'product.name', 'price.price').", max_length=255)),
                ('transform', models.CharField(blank=True, help_text="Optional transform function to apply (e.g., 'upper', 'decimal').", max_length=50, null=True)),
                ('is_required', models.BooleanField(default=False, help_text='If true, the target field must be present after mapping.')),
                ('map_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_details', to='imports.importmapset')),
            ],
            options={
                'verbose_name': 'Import Map Detail',
                'verbose_name_plural': 'Import Map Details',
            },
        ),
        migrations.AddConstraint(
            model_name='importmapset',
            constraint=models.UniqueConstraint(fields=('organization', 'supplier', 'source_type', 'valid_from'), name='uq_mapset_org_supplier_type_validfrom'),
        ),
        migrations.AddConstraint(
            model_name='importmapdetail',
            constraint=models.UniqueConstraint(fields=('map_set', 'source_path', 'target_path'), name='uq_mapdetail_set_source_target'),
        ),
    ]
