# Generated by Django 5.2.5 on 2025-08-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importglobaldefaultline',
            name='transform',
            field=models.CharField(blank=True, choices=[('uppercase', 'Uppercase'), ('lowercase', 'Lowercase'), ('strip', 'Trim Whitespace'), ('int', 'Convert to Integer'), ('decimal', 'Convert to Decimal'), ('bool', 'Convert to Boolean')], help_text='Optional transformation to apply to the value.', max_length=50, null=True),
        ),
    ]
