# Generated by Django 5.2.5 on 2025-08-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrawrecord',
            name='error_message',
            field=models.TextField(blank=True, help_text='Detailed error message if processing failed.', null=True),
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='imported_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was imported.', null=True),
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='is_error',
            field=models.BooleanField(default=False, help_text='True if processing this record failed.'),
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='True if this record has been successfully imported into ERP tables.'),
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this record has been retried for processing.'),
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='supplier_product_reference',
            field=models.CharField(blank=True, db_index=True, help_text="Supplier's article reference (e.g., supplier SKU or manufacturer number) for fast lookup.", max_length=255, null=True),
        ),
    ]
