# Generated by Django 5.2.5 on 2025-08-26 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='imports.importrun')),
            ],
            options={
                'verbose_name': 'Import Error Log',
                'verbose_name_plural': 'Import Error Logs',
            },
        ),
    ]
