# Generated by Django 5.2.5 on 2025-08-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_importerrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportGlobalDefaultSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('valid_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Import Global Default Set',
                'verbose_name_plural': 'Import Global Default Sets',
            },
        ),
    ]
