# Generated by Django 5.2.5 on 2025-08-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_importglobaldefaultline_transform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTransformType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for this transform (e.g., uppercase, int, bool).', max_length=50, unique=True)),
                ('description', models.CharField(help_text='Human-readable description of what this transform does.', max_length=255)),
            ],
            options={
                'verbose_name': 'Import Transform Type',
                'verbose_name_plural': 'Import Transform Types',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='importglobaldefaultline',
            name='transform',
            field=models.ForeignKey(blank=True, help_text='Transform to apply to this field (FK instead of free text).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_lines', to='imports.importtransformtype'),
        ),
    ]
