# Generated by Django 5.2.5 on 2025-08-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importglobaldefaultset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportGlobalDefaultLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_path', models.CharField(max_length=255)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('transform', models.CharField(blank=True, max_length=50, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glocal_default_lines', to='imports.importglobaldefaultset')),
            ],
            options={
                'verbose_name': 'Import Global Default Line',
                'verbose_name_plural': 'Import Global Default Lines',
            },
        ),
    ]
