# Generated by Django 5.2.5 on 2025-08-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_rename_imported_at_importrawrecord_product_imported_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importrawrecord',
            old_name='error_message',
            new_name='error_message_price_import',
        ),
        migrations.RenameField(
            model_name='importrawrecord',
            old_name='is_error',
            new_name='is_price_import_error',
        ),
        migrations.RenameField(
            model_name='importrawrecord',
            old_name='retry_count',
            new_name='retry_count_price_import',
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='error_message_product_import',
            field=models.TextField(blank=True, help_text='Detailed error message if processing failed.', null=True),
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='is_product_import_error',
            field=models.BooleanField(default=False, help_text='True if processing this record failed.'),
        ),
        migrations.AddField(
            model_name='importrawrecord',
            name='retry_count_product_import',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this record has been retried for processing.'),
        ),
        migrations.AddIndex(
            model_name='importrawrecord',
            index=models.Index(fields=['product_is_imported'], name='idx_rawrecord_product_imported'),
        ),
        migrations.AddIndex(
            model_name='importrawrecord',
            index=models.Index(fields=['price_is_imported'], name='idx_rawrecord_price_imported'),
        ),
    ]
