# Generated by Django 5.2.5 on 2025-09-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importtransformtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='map_set',
            field=models.ForeignKey(blank=True, help_text='The mapping set that was applied for this import run.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='imports.importmapset'),
        ),
    ]
