# Generated by Django 5.2.5 on 2025-09-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importrun_map_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrawrecord',
            name='normalized_data',
            field=models.JSONField(blank=True, help_text='Normalized data extracted from the raw payload for easier processing.', null=True),
        ),
    ]
